version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_mgmt_system
  app:
    build: .
    image: event_mgmt_system
    ports:
      - 5000:5000
    depends_on:
      - postgres